apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    namespace "dsw.zxing"
    defaultConfig {
        minSdkVersion 19
        targetSdkVersion 23
        versionCode 108
        versionName "4.7.8"
        multiDexEnabled false
    }
}

dependencies { 
    implementation project(":core")
}
